# Auto Generated Dockerfile

FROM ballerina/ballerina:0.982.0
LABEL maintainer="dev@ballerina.io"

COPY hello_world_docker.balx /home/ballerina 

EXPOSE  9090

CMD ballerina run hello_world_docker.balx
